#!/bin/bash

set -e

if [ -z "$1" ]; then
    echo "usage: templatize PACKAGE-NAME"
    exit 1
fi

package=$1
thisdir=$(cd $(dirname $0) && pwd)

echo "* branching $package"
bzr branch $thisdir $package
cd $package

package_uc=$(echo $package | tr '[:lower:]-' '[:upper:]_')
package_un=$(echo $package | tr '-' '_')
year=$(date +%Y)

for i in `bzr inventory --kind file`; do
    echo "* templatizing $i"
    perl -i -p -e "s/_template/_${package_un}/g" $i
    perl -i -p -e "s/template_/${package_un}_/g" $i
    perl -i -p -e "s/template/$package/g" $i
    perl -i -p -e "s/TEMPLATE/$package_uc/g" $i
    perl -i -p -e "s/2004/$year/g" $i
    if basename $i | grep -q template; then
        newname="$(dirname $i)/$(echo $(basename $i) | sed -e "s/template/$package/")"
        echo "* moving file $i to $newname"
        bzr mv $i $newname
    fi
done

for i in `bzr inventory --kind directory`; do
    if echo $i | grep -q template; then
        newname=$(echo $i | sed -e "s/template/$package/")
        echo "* moving directory $i to $newname"
        mv $i $newname
    fi
done

echo "* removing templatize script"
rm templatize
