
@c %start of fragment

@node Undocumented
@chapter Undocumented
The following symbols, if any, have not been properly documented.

@section (gnome gw clutter-glx)
@defvar clutter-x11-event-sequence-get-touch-detail
@end defvar

@defvar clutter-x11-texture-pixmap-new-with-pixmap
@end defvar

@defvar clutter-x11-texture-pixmap-new-with-window
@end defvar

@defvar clutter-x11-texture-pixmap-set-automatic
@end defvar

@defvar clutter-x11-texture-pixmap-set-pixmap
@end defvar

@defvar clutter-x11-texture-pixmap-set-window
@end defvar

@defvar clutter-x11-texture-pixmap-sync-window
@end defvar

@defvar clutter-x11-texture-pixmap-update-area
@end defvar


@c %end of fragment
