
@c %start of fragment

@node GstMiniObject
@chapter GstMiniObject
Lightweight base class for the GStreamer object hierarchy

@section Overview
@code{<gst-mini-object>} is a baseclass like @code{<gobject>}, but has been
stripped down of features to be fast and small. It offers sub-classing and
ref-counting in the same way as @code{<gobject>} does. It has no properties and
no signal-support though.

Last reviewed on 2005-11-23 (0.9.5)

@section Usage
@include defuns-gstminiobject.xml.texi

@c %end of fragment
