
@c %start of fragment

@node GstVersion
@chapter GstVersion
GStreamer version macros.

@section Overview
Use the GST_VERSION_* macros e.g. when defining own plugins. The GStreamer
runtime checks if these plugin and core version match and refuses to use a
plugin compiled against a different version of GStreamer. You can also use the
macros to keep the GStreamer version information in your application.

Use the @code{gst-version} function if you want to know which version of
GStreamer you are currently linked against.

The version macros get defined by including "gst/gst.h".

@section Usage
@include defuns-gstversion.xml.texi

@c %end of fragment
