
@c %start of fragment

@node GstFilter
@chapter GstFilter
A utility function to filter GLists.

@section Overview
@c (title "Filtering a list")
@example 

    GList *node;
    GstObject *result = NULL;
    
    node = gst_filter_run (list, (GstFilterFunc) my_filter, TRUE, NULL);
    if (node) @{
      result = GST_OBJECT (node->data);
      gst_object_ref (result);
      gst_list_free (node);
    @}
  
@end example

@section Usage
@include defuns-gstfilter.xml.texi

@c %end of fragment
