
@c %start of fragment

@node GstQuery
@chapter GstQuery
Dynamically register new query types. Provide functions to create queries, and
to set and parse values in them.

@section Overview
GstQuery functions are used to register a new query types to the gstreamer core.
Query types can be used to perform queries on pads and elements.

Queries can be created using the @code{gst-query-new-xxx} functions. Query
values can be set using @code{gst-query-set-xxx}, and parsed using
@code{gst-query-parse-xxx} helpers.

The following example shows how to query the duration of a pipeline:

@c (title "Query duration on a pipeline")
@example 

 GstQuery *query;
 gboolean res;
 query = gst_query_new_duration (GST_FORMAT_TIME);
 res = gst_element_query (pipeline, query);
 if (res) @{
   gint64 duration;
   gst_query_parse_duration (query, NULL, &duration);
   g_print ("duration = %"GST_TIME_FORMAT, GST_TIME_ARGS (duration));
 @}
 else @{
   g_print ("duration query failed...");
 @}
 gst_query_unref (query);
 
@end example

Last reviewed on 2006-02-14 (0.10.4)

@section Usage
@include defuns-gstquery.xml.texi

@c %end of fragment
