#!/bin/bash

file=$1
comment=$2

if test -z "$file" -o -z "$comment"; then
    echo "usage: $0 FILE COMMENT" >&2
    exit 1
fi

file=`cd $(dirname $file) && pwd`/`basename $file`
changelog_path=`dirname $file`
file_relpath=
until test -f $changelog_path/ChangeLog; do
    if test $changelog_path = /; then
        echo "No ChangeLog found for $file" >&2
        exit 1
    fi
    file_relpath=`basename $changelog_path`/$file_relpath
    changelog_path=`dirname $changelog_path`
done
    
test -f $changelog_path/ChangeLog || exit 100
changelog=$changelog_path/ChangeLog

mv $changelog ${changelog}.old
echo -n `date +"%Y-%m-%d"` > $changelog
echo "  `bzr whoami | sed -e 's,<, <,'`" >> $changelog
echo >> $changelog
IFS="
"
for line in `echo "* $file_relpath$(basename $file): $comment" | fold -s -w 66`; do
    echo -e "\t$line" >> $changelog
done
echo >> $changelog

cat ${changelog}.old >> $changelog
