#!/bin/bash

set -e

package=$1
version=$2

if test -z "$package" -o -z "$version"; then
    echo "usage: $0 PACKAGE VERSION" >&2
    exit 1
fi

dir=$(cd `dirname $0`/../.. && pwd)
echo "* commit-release in $dir"
cd $dir

for i in `find . -name VERSION`; do
    echo "* setting $i to $version"
    echo $version > $i
    ( cd $(dirname $i); bzr commit -m "Bumped to $version." VERSION )
done

for i in *; do
    if test -d $i/.bzr; then
       packages="$packages $i";
    fi
done

# include pkg in the list
packages="$packages ."

for i in $packages; do
    (cd $i && bzr commit --unchanged -m "Released $package $version" && bzr tag $version)
done
