
@c %start of fragment

@node GstMessage
@chapter GstMessage
Lightweight objects to signal the application of pipeline events

@section Overview
Messages are implemented as a subclass of @code{<gst-mini-object>} with a
generic @code{<gst-structure>} as the content. This allows for writing custom
messages without requiring an API change while allowing a wide range of
different types of messages.

Messages are posted by objects in the pipeline and are passed to the application
using the @code{<gst-bus>}.

The basic use pattern of posting a message on a @code{<gst-bus>} is as follows:

@c (title "Posting a " (code "<gst-message>"))
@example 

   gst_bus_post (bus, gst_message_new_eos());
  
@end example

A @code{<gst-element>} usually posts messages on the bus provided by the parent
container using @code{gst-element-post-message}.

Last reviewed on 2005-11-09 (0.9.4)

@section Usage
@include defuns-gstmessage.xml.texi

@c %end of fragment
