
@c %start of fragment

@node ClutterBehaviourBspline
@chapter ClutterBehaviourBspline
A behaviour interpolating position along a B-Spline

@section Overview
@code{<clutter-behaviour-bspline>} interpolates actors along a defined B-Spline
path.

A bezier spline is a set of cubic bezier curves defined by a sequence of control
points given when creating a new @code{<clutter-behaviour-bspline>} instance.

Additional bezier curves can be added to the end of the bspline using
clutter_behaviour_bspline_append_* family of functions, control points can be
moved using @code{clutter-behaviour-bspline-adjust}. The bspline can be split
into two with @code{clutter-behaviour-bspline-split}, and bsplines can be
concatenated using @code{clutter-behaviour-bspline-join}.

Each time the behaviour reaches a point on the path, the "knot-reached" signal
is emitted.

@section Usage
@include defuns-clutter-behaviour-bspline.xml.texi

@c %end of fragment
