
@c %start of fragment

@node GstSystemClock
@chapter GstSystemClock
Default clock that uses the current system time

@section Overview
The GStreamer core provides a GstSystemClock based on the system time.
Asynchronous callbacks are scheduled from an internal thread.

Clock implementors are encouraged to subclass this systemclock as it implements
the async notification.

Subclasses can however override all of the important methods for sync and async
notifications to implement their own callback methods or blocking wait
operations.

Last reviewed on 2006-03-08 (0.10.4)

@section Usage
@include defuns-gstsystemclock.xml.texi

@c %end of fragment
