
@c %start of fragment

@node Clutter Effects
@chapter Clutter Effects
Utility Class for basic visual effects

@section Overview
The @code{<clutter-effect-template>} class provides a simple API for applying
pre-defined effects to a single actor. It works as a wrapper around the
@code{<clutter-behaviour>} objects

@section Usage
@include defuns-clutter-effect.xml.texi

@c %end of fragment
