
@c %start of fragment

@node ClutterCloneTexture
@chapter ClutterCloneTexture
Actor for cloning existing textures in an efficient way.

@section Overview
@code{<clutter-clone-texture>} allows the cloning of existing
@code{<clutter-texture>} based actors whilst saving underlying graphics
resources.

@section Usage
@include defuns-clutter-clone-texture.xml.texi

@c %end of fragment
