#!/bin/bash

mod=$(basename $(cd . && pwd))
log=`bzr diff ChangeLog | egrep '^\+' | tail -n +2 | cut -d+ -f2`
if test -n "$1"; then extralog="$@\n"; else extralog=""; fi

if test -z "$log"; then
    echo "* $mod: no changes" >&2
    exit 1
else
    echo -e "* $mod: committing with changes:\n$extralog$log"
    bzr commit -m "$extralog$log"
fi