#!/bin/sh

package=$1
version=$2

if test -z "$package" -o -z "$version"; then
    echo "usage: $0 PACKAGE VERSION" >&2
    exit 1
fi

dir=$(cd `dirname $0`/.. && pwd)
echo "* commit-release in $dir"
cd $dir

for i in `find . -name VERSION`; do
    echo "* setting $i to $version"
    echo $version > $i
    ./scripts/add-changelog-entry $i "Bumped to $version."
done

for i in *; do
    if test -d $i/.bzr; then
       packages="$packages $i";
    fi
done

# include pkg in the list
packages="$packages ."

for i in $packages; do
    ./scripts/changelog-log-release $i $package $version
    (cd $i && bzr commit -m "Released $package $version")
done
