#!/bin/sh

dir=$(cd `dirname $0`/.. && pwd)
cd $dir

for i in *; do
    if test -d $i/{arch}; then
       packages="$packages $i";
    fi
done

# include pkg in the list
packages="$packages ."

for i in $packages; do
  if (cd $i && tla changes | grep -q ChangeLog); then
    echo "* $i: tla commit -m \`tla log-for-merge\` $@"
    (cd $i && tla commit -s "`tla log-for-merge`" "$@")
  fi
done
