#!/bin/sh

command=$1
shift

dir=$(cd `dirname $0`/.. && pwd)
echo "* for-each-pkg in $dir"
cd $dir

for i in *; do
    if test -d $i/{arch}; then
       packages="$packages $i";
    fi
done

# include pkg in the list
packages="$packages ."

for i in $packages; do
    echo "* $i: $command $@"
    ( cd $i; $command $@ )
done
