#!/bin/sh

year=`date +%Y`

if test -n "$TLA";
  TLA=tla
fi

while [ -n "$1" ]; do
  if echo "$TLA" | grep -q baz; then
    $TLA branch "guile-gnome-devel@gnu.org--$year/$1--dev--0" "guile-gnome-$1--dev--0"
  else
    $TLA tag -S "guile-gnome-devel@gnu.org--$year/$1--dev--0" "guile-gnome-$1--dev--0"
  fi
  shift
done
