#!/bin/bash

root=`cd $(dirname $0)/.. && pwd`
if test -z "$1"; then
    echo "usage: $0 BASE-URL"
    echo "pushes out all packages in $root to BASE-URL"
    exit 1
fi
baseurl=$1

for dir in $root/*; do
    if test -d $dir -a -d $dir/.bzr; then
        package=`basename $dir`
        echo "pushing $dir to $baseurl/$package"
        ( cd $dir; bzr push $baseurl/$package )
    fi
done
echo "pushing $root to $baseurl/pkg"
( cd $root; bzr push $baseurl/pkg )
