#!/bin/zsh

set -e

getanswer_yn() {
  answer=invalid
  while [ "$answer" = invalid ]; do
    echo -n "$1 [Y/n] "; read answer
    if [ -z "$answer" ]; then
      answer=y
    fi
    if [ ! "$answer" = y -a ! "$answer" = n ]; then
      answer=invalid
      echo "please answer y or n"
    fi
  done
}

mirror=""
lastlog=""

while [ -n "$1" ]; do
  case "$1" in 
    --mirror) mirror=y ;;
    --nomirror) mirror=n ;;
    --lastlog) lastlog=y ;;
    *) break ;;
  esac
  shift
done

if [ -z "$1" ]; then
  lastmsg=`tla revisions -s | awk '/^  / { line = $0; sub(/^[ ]+/, "", line); } END { print line; }'`
  if [ -z "$lastlog" ]; then
    getanswer_yn "use last log message ($lastmsg)?"
    lastlog=$answer
  fi
  if [ $lastlog = y ]; then
    msg=$lastmsg
  else
    echo Usage: submit-merge "message"
    exit 1
  fi
else
  msg=$1
fi
    

if [ ! -e '{arch}/+upstream' ]; then
  echo "Must create {arch}/+upstream"
  exit 1
fi

tree_version=$(tla tree-version)

if [ -z "$mirror" ]; then
  getanswer_yn "mirror?"
  mirror=$answer
fi
if [ $mirror = y ]; then
    tla archive-mirror $(tla parse-package-name --arch "$tree_version")
fi

echo star-merge "$tree_version" "$(cat '{arch}/+upstream')" | agpg --clearsign | mail -s "PQM-REQUEST $msg" rotty@debian.org
