#!/bin/sh

command=$1
shift

if [ ! -d '{arch}' -o ! -d ../configs/gnu.org ]; then
  echo "must call add-upstream from top-level project directory"
  exit 1
fi

for i in *; do
    if test -d $i/{arch}; then
       packages="$packages $i";
    fi
done

for i in $packages; do
    echo tla $command -d $i $@
    tla $command -d $i $@
done
