#!/bin/bash
for i in `tla tree-lint -t`; do
  echo "Marking '$i' as precious"
  inv=`dirname $i`/.arch-inventory
  echo "precious ^$(basename $i)\$" >> $inv
  if ! tla id --silent $inv; then
    echo "Adding $inv as source"
    tla add -i `uuidgen` $inv;
  fi
done
