#!/bin/sh

set -e

if test -z "$TLA"; then
  TLA=`which tla || which baz`
fi

if ! $TLA tree-id 2>&1 >/dev/null; then
  echo "Error: not in a valid arch working tree." >&2
  exit 1
fi

usage() {
  echo "usage: $0 [--full] [FQVN]" >&2
  echo >&2
  echo "Prints the patches from the current tree missing in FQVN," >&2
  echo "defaulting to {arch}/+upstream." >&2
  exit 1
}

if test $# -ge 1 -a "$1" = "--full"; then
  full=true
  shift
else
  full=false
fi

if test $# -eq 0; then
  if test -f `$TLA tree-root`/{arch}/+upstream; then
    upstream=`cat $($TLA tree-root)/{arch}/+upstream`
  else
    echo "Error: No upstream version specified and {arch}/+upstream not found." >&2
    exit 1
  fi
else
  test $# -eq 1 || usage
  upstream=$1
fi

dir=`mktemp -d`
version=`$TLA tree-version`

$TLA get -s $upstream $dir/working-copy
missing=`$TLA missing -d $dir/working-copy $version`

if `$full`; then
  for i in $missing; do
    $TLA cat-archive-log $i
  done
else
  for i in $missing; do echo $i; done
fi

rm -rf $dir
