\input texinfo   @c -*-texinfo-*-
@c %**start of header
@setfilename guile-gnome-clutter.info
@settitle Guile-Clutter
@c %**end of header

@include version.texi

@copying 
This manual is for @code{(gnome clutter)} (version @value{VERSION}, updated
@value{UPDATED})

Copyright 2006,2007,2008 OpenedHand LTD

Copyright 2009,2010,2011,2012 Intel Corporation

@quotation 
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.1 or
any later version published by the Free Software Foundation with no
Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts. You
may obtain a copy of the GNU Free Documentation License from the Free
Software Foundation by visiting their Web site or by writing to:

@quotation
The Free Software Foundation, Inc.,
59 Temple Place - Suite 330,
Boston, MA 02111-1307,
USA
@end quotation
@end quotation

@end copying

@dircategory The Algorithmic Language Scheme
@direntry 
* Guile-Clutter: (guile-gnome-clutter.info).  A fast graphical canvas toolkit.
@end direntry

@titlepage 
@title Guile-GNOME: Clutter
@subtitle version @value{VERSION}, updated @value{UPDATED}
@author Matthew Allum and OpenedHand LTD
@author Intel Corporation
@page 
@vskip 0pt plus 1filll
@insertcopying 
@end titlepage

@ifnottex 
@node Top
@top Guile-Clutter

@insertcopying 
@menu
* Overview::               About Clutter and its Guile bindings.

* ClutterAction:: Abstract class for event-related logic
* ClutterActorMeta:: Base class of actor modifiers
* ClutterActor:: Base abstract class for all visual stage actors.
* ClutterAlignConstraint:: A constraint aligning the position of an actor
* ClutterAnimatable:: Interface for animatable classes.
* ClutterAnimator:: Multi-actor tweener
* Implicit Animations:: Simple implicit animations.
* ClutterAlpha:: A class for calculating an alpha value as a function of time.
* ClutterBackend:: Backend abstraction
* ClutterBehaviourDepth:: A behaviour controlling the Z position
* ClutterBehaviourEllipse:: A behaviour interpolating position along an ellipse
* ClutterBehaviourOpacity:: Behaviour controlling the opacity
* ClutterBehaviourPath:: A behaviour interpolating position along a path
* ClutterBehaviourRotate:: A behaviour controlling rotation
* ClutterBehaviourScale:: A behaviour controlling scale
* ClutterBehaviour:: Class for providing behaviours to actors
* ClutterBindConstraint:: A constraint binding the position or size of an actor
* ClutterBinLayout:: A simple layout manager
* ClutterBlurEffect:: A blur effect
* ClutterBoxLayout:: A layout manager arranging children on a single line
* ClutterBox:: A generic layout container
* Key Bindings:: Pool for key bindings.
* ClutterChildMeta:: Wrapper for actors inside a container
* ClutterCairoTexture:: Texture with Cairo integration.
* ClutterClickAction:: Action for clickable actors
* ClutterClone:: An actor that displays a clone of a source actor.
* ClutterColorizeEffect:: A colorization effect
* Colors:: Color management and manipulation.
* ClutterConstraint:: Abstract class for constraints on position or size
* ClutterContainer:: An interface for implementing container actors
* ClutterDeformEffect:: A base class for effects deforming the geometry of an actor
* ClutterDesaturateEffect:: A desaturation effect
* ClutterDeviceManager:: Maintains the list of input devices
* ClutterDragAction:: Action enabling dragging on actors
* ClutterDropAction:: An action for drop targets
* ClutterEffect:: Base class for actor effects
* Events:: User and window system events
* Features:: Query GL features at runtime
* ClutterFixedLayout:: A fixed layout manager
* ClutterFlowLayout:: A reflowing layout manager
* ClutterGestureAction:: Action for gesture gestures
* ClutterGroup:: Actor class containing multiple children. actors.
* ClutterInputDevice:: An input device managed by Clutter
* Value intervals:: An object holding an interval of two values.
* ClutterLayoutManager:: Layout managers base class
* ClutterLayoutMeta:: Wrapper for actors inside a layout manager
* ClutterListModel:: List model implementation
* General:: Various 'global' clutter functions.
* ClutterMedia:: An interface for controlling playback of media data.
* ClutterModelIter:: Iterates through a model
* ClutterModel:: A generic model implementation
* ClutterOffscreenEffect:: Base class for effects using offscreen buffers
* ClutterPageTurnEffect:: A page turning effect
* ClutterPathConstraint:: A constraint that follows a path
* ClutterPath:: Paths with straight lines and bezier curves.
* ClutterRectangle:: An actor that displays a simple rectangle.
* ClutterSettings:: Settings configuration
* ClutterScore:: Controller for multiple timelines
* ClutterScriptable:: Override the UI definition parsing
* ClutterScript:: Loads a scene from UI definition data
* ClutterShaderEffect:: Base class for shader effects
* Shaders:: Programmable pipeline abstraction
* Stage Manager:: Maintains the list of stages
* ClutterSnapConstraint:: A constraint snapping two actors together
* ClutterStage:: Top level visual element to which actors are placed.
* ClutterState:: State machine with animated transitions
* ClutterSwipeAction:: Action for swipe gestures
* ClutterTableLayout:: A layout manager arranging children in rows and columns
* ClutterText:: An actor for displaying and editing text.
* ClutterTexture:: An actor for displaying and manipulating images.
* ClutterTimeline:: A class for time-based events
* Unit conversion:: A logical distance unit.
* Utilities:: Misc utility functions.
* Versioning Macros:: Versioning utility macros


* Undocumented::           Undocumented functions.

* Type Index::
* Function Index::
@end menu

@end ifnottex

@iftex 
@shortcontents 
@end iftex

@include overview.texi

@include section-clutter-action.xml.texi
@include section-clutter-actor-meta.xml.texi
@include section-clutter-actor.xml.texi
@include section-clutter-align-constraint.xml.texi
@include section-clutter-alpha.xml.texi
@include section-clutter-animatable.xml.texi
@include section-clutter-animation.xml.texi
@include section-clutter-animator.xml.texi
@include section-clutter-backend.xml.texi
@include section-clutter-behaviour-depth.xml.texi
@include section-clutter-behaviour-ellipse.xml.texi
@include section-clutter-behaviour-opacity.xml.texi
@include section-clutter-behaviour-path.xml.texi
@include section-clutter-behaviour-rotate.xml.texi
@include section-clutter-behaviour-scale.xml.texi
@include section-clutter-behaviour.xml.texi
@include section-clutter-bin-layout.xml.texi
@include section-clutter-bind-constraint.xml.texi
@include section-clutter-binding-pool.xml.texi
@include section-clutter-blur-effect.xml.texi
@include section-clutter-box-layout.xml.texi
@include section-clutter-box.xml.texi
@include section-clutter-cairo-texture.xml.texi
@include section-clutter-child-meta.xml.texi
@include section-clutter-click-action.xml.texi
@include section-clutter-clone.xml.texi
@include section-clutter-color.xml.texi
@include section-clutter-colorize-effect.xml.texi
@include section-clutter-constraint.xml.texi
@include section-clutter-container.xml.texi
@include section-clutter-deform-effect.xml.texi
@include section-clutter-desaturate-effect.xml.texi
@include section-clutter-device-manager.xml.texi
@include section-clutter-drag-action.xml.texi
@include section-clutter-drop-action.xml.texi
@include section-clutter-effect.xml.texi
@include section-clutter-event.xml.texi
@include section-clutter-feature.xml.texi
@include section-clutter-fixed-layout.xml.texi
@include section-clutter-flow-layout.xml.texi
@include section-clutter-gesture-action.xml.texi
@include section-clutter-group.xml.texi
@include section-clutter-input-device.xml.texi
@include section-clutter-interval.xml.texi
@include section-clutter-layout-manager.xml.texi
@include section-clutter-layout-meta.xml.texi
@include section-clutter-list-model.xml.texi
@include section-clutter-main.xml.texi
@include section-clutter-media.xml.texi
@include section-clutter-model-iter.xml.texi
@include section-clutter-model.xml.texi
@include section-clutter-offscreen-effect.xml.texi
@include section-clutter-page-turn-effect.xml.texi
@include section-clutter-path-constraint.xml.texi
@include section-clutter-path.xml.texi
@include section-clutter-rectangle.xml.texi
@include section-clutter-score.xml.texi
@include section-clutter-script.xml.texi
@include section-clutter-scriptable.xml.texi
@include section-clutter-settings.xml.texi
@include section-clutter-shader-effect.xml.texi
@include section-clutter-shader.xml.texi
@include section-clutter-snap-constraint.xml.texi
@include section-clutter-stage-manager.xml.texi
@include section-clutter-stage.xml.texi
@include section-clutter-state.xml.texi
@include section-clutter-swipe-action.xml.texi
@include section-clutter-table-layout.xml.texi
@include section-clutter-text.xml.texi
@include section-clutter-texture.xml.texi
@include section-clutter-timeline.xml.texi
@include section-clutter-units.xml.texi
@include section-clutter-util.xml.texi
@include section-clutter-version.xml.texi

@include undocumented.texi

@node Type Index
@unnumbered Type Index
@printindex tp
@node Function Index
@unnumbered Function Index
@printindex fn
@bye
