
@c %start of fragment

@node Events
@chapter Events
User and window system events

@section Overview
Windowing events handled by Clutter.

The events usually come from the windowing backend, but can also be
synthesized by Clutter itself or by the application code.

@section Usage
@include defuns-clutter-event.xml.texi

@c %end of fragment
