
@c %start of fragment

@node Shaders
@chapter Shaders
Programmable pipeline abstraction

@section Overview
@code{<clutter-shader>} is an object providing an abstraction over the
OpenGL programmable pipeline. By using @code{<clutter-shader>}s is
possible to override the drawing pipeline by using small programs also
known as "shaders".

@code{<clutter-shader>} is available since Clutter 0.6.

@code{<clutter-shader>} is deprecated since Clutter 1.8; use
@code{<clutter-shader-effect>} in newly written code.

@section Usage
@include defuns-clutter-shader.xml.texi

@c %end of fragment
