
@c %start of fragment

@node ClutterText
@chapter ClutterText
An actor for displaying and editing text

@section Overview
@code{<clutter-text>} is an actor that displays custom text using Pango
as the text rendering engine.

@code{<clutter-text>} also allows inline editing of the text if the
actor is set editable using @code{clutter-text-set-editable}.

Selection using keyboard or pointers can be enabled using
@code{clutter-text-set-selectable}.

@code{<clutter-text>} is available since Clutter 1.0

@section Usage
@include defuns-clutter-text.xml.texi

@c %end of fragment
