
@c %start of fragment

@node Features
@chapter Features
Run-time detection of Clutter features

@section Overview
Parts of Clutter depend on the underlying platform, including the
capabilities of the backend used and the OpenGL features exposed through
the Clutter and COGL API.

It is possible to ask whether Clutter has support for specific features
at run-time.

See also @code{cogl-get-features} and @code{<cogl-feature-flags>}

@section Usage
@include defuns-clutter-feature.xml.texi

@c %end of fragment
