
@c %start of fragment

@node Win32 Specific Support
@chapter Win32 Specific Support
Win32 specific API

@section Overview
The Win32 backend for Clutter provides some specific API, allowing integration
with the Win32 API for embedding and manipulating the stage window.

The ClutterWin32 API is available since Clutter 0.8

@section Usage
@include defuns-clutter-win32.xml.texi

@c %end of fragment
