
@c %start of fragment

@node ClutterImage
@chapter ClutterImage
Image data content

@section Overview
@code{<clutter-image>} is a @code{<clutter-content>} implementation that
displays image data.

@example 
@c (http://www.w3.org/2001/XInclude:include (@ (parse "text") (href "../../../../examples/image-content.c")) (c (% (all "(http://www.w3.org/2001/XInclude:fallback \"FIXME: MISSING XINCLUDE CONTENT\")"))))
@end example

@code{<clutter-image>} is available since Clutter 1.10.

@section Usage
@include defuns-clutter-image.xml.texi

@c %end of fragment
