
@c %start of fragment

@node ClutterSettings
@chapter ClutterSettings
Settings configuration

@section Overview
Clutter depends on some settings to perform operations like detecting
multiple button press events, or font options to render text.

Usually, Clutter will strive to use the platform's settings in order to
be as much integrated as possible. It is, however, possible to change
these settings on a per-application basis, by using the
@code{<clutter-settings>} singleton object and setting its properties.
It is also possible, for toolkit developers, to retrieve the settings
from the @code{<clutter-settings>} properties when implementing new UI
elements, for instance the default font name.

@code{<clutter-settings>} is available since Clutter 1.4

@section Usage
@include defuns-clutter-settings.xml.texi

@c %end of fragment
