
@c %start of fragment

@node ClutterBoxLayout
@chapter ClutterBoxLayout
A layout manager arranging children on a single line

@section Overview
The @code{<clutter-box-layout>} is a @code{<clutter-layout-manager>}
implementing the following layout policy:

@itemize 
@item
@item
@item
@item
@item
@item
@end itemize

all children are arranged on a single line;

the axis used is controlled by the @code{<“orientation”>} property;

the order of the packing is determined by the @code{<“pack-start”>}
boolean property;

each child will be allocated to its natural size or, if
@code{<“x-expand”>}/@code{<“y-expand”>} is set, the available
size;

honours the @code{<clutter-actor>}'s @code{<“x-align”>} and
@code{<“y-align”>} properties to fill the available size;

if the @code{<“homogeneous”>} boolean property is set, then all
widgets will get the same size, ignoring expand settings and the
preferred sizes

@c (title "Box layout")
The image shows a @code{<clutter-box-layout>} with the
@code{<“vertical”>} property set to @samp{@code{#f}}.

It is possible to control the spacing between children of a
@code{<clutter-box-layout>} by using
@code{clutter-box-layout-set-spacing}.

@code{<clutter-box-layout>} is available since Clutter 1.2

@section Usage
@include defuns-clutter-box-layout.xml.texi

@c %end of fragment
