
@c %start of fragment

@node ClutterBehaviourEllipse
@chapter ClutterBehaviourEllipse
A behaviour interpolating position along an ellipse

@section Overview
@code{<clutter-behaviour-ellipse>} interpolates actors along a path defined by
an ellipse.

Note, on applying an ellipse behaviour to an actor its position will be set to
what is dictated by the ellipses initial position.

@section Usage
@include defuns-clutter-behaviour-ellipse.xml.texi

@c %end of fragment
