
@c %start of fragment

@node ClutterGestureAction
@chapter ClutterGestureAction
Action for gesture gestures

@section Overview
@code{<clutter-gesture-action>} is a sub-class of
@code{<clutter-action>} that implements the logic for recognizing
gesture gestures. It listens for low level events such as
@code{<clutter-button-event>} and @code{<clutter-motion-event>} on the
stage to raise the @code{<"gesture-begin">},
@code{<"gesture-progress">}, and * @code{<"gesture-end">} signals.

To use @code{<clutter-gesture-action>} you just need to apply it to a
@code{<clutter-actor>} using @code{clutter-actor-add-action} and connect
to the signals:

@example 

  ClutterAction *action = clutter_gesture_action_new ();

  clutter_actor_add_action (actor, action);

  g_signal_connect (action, "gesture-begin", G_CALLBACK (on_gesture_begin), NULL);
  g_signal_connect (action, "gesture-progress", G_CALLBACK (on_gesture_progress), NULL);
  g_signal_connect (action, "gesture-end", G_CALLBACK (on_gesture_end), NULL);
@end example

@section Usage
@include defuns-clutter-gesture-action.xml.texi

@c %end of fragment
