
@c %start of fragment

@node ClutterPathConstraint
@chapter ClutterPathConstraint
A constraint that follows a path

@section Overview
@code{<clutter-path-constraint>} is a simple constraint that modifies
the allocation of the @code{<clutter-actor>} to which it has been
applied using a @code{<clutter-path>}.

By setting the @code{<"offset">} property it is possible to control how
far along the path the @code{<clutter-actor>} should be.

ClutterPathConstraint is available since Clutter 1.6.

@section Usage
@include defuns-clutter-path-constraint.xml.texi

@c %end of fragment
