
@c %start of fragment

@node ClutterBinLayout
@chapter ClutterBinLayout
A simple layout manager

@section Overview
@code{<clutter-bin-layout>} is a layout manager which implements the
following policy:

@itemize 
@item
the preferred size is the maximum preferred size between all the
children of the container using the layout;

@item
each child is allocated in "layers", on on top of the other;

@item
for each layer there are horizontal and vertical alignment policies.

@end itemize

@c (title "Bin layout")
The image shows a @code{<clutter-bin-layout>} with three layers: a
background @code{<clutter-cairo-texture>}, set to fill on both the X and
Y axis; a @code{<clutter-texture>}, set to center on both the X and Y
axis; and a @code{<clutter-rectangle>}, set to
@samp{CLUTTER_BIN_ALIGNMENT_END} on both the X and Y axis.

@c (example (@ (id "example-clutter-bin-layout")))
@c (title "How to pack actors inside a BinLayout")
@example 
@c (http://www.w3.org/2001/XInclude:include (@ (parse "text") (href "../../../../examples/bin-layout.c")) (c (% (all "(http://www.w3.org/2001/XInclude:fallback \"FIXME: MISSING XINCLUDE CONTENT\")"))))
@end example

@code{<clutter-bin-layout>} is available since Clutter 1.2

@section Usage
@include defuns-clutter-bin-layout.xml.texi

@c %end of fragment
