
@c %start of fragment

@node ClutterRectangle
@chapter ClutterRectangle
An actor that displays a simple rectangle.

@section Overview
@code{<clutter-rectangle>} is a @code{<clutter-actor>} which draws a
simple filled rectangle.

@section Usage
@include defuns-clutter-rectangle.xml.texi

@c %end of fragment
