
@c %start of fragment

@node ClutterDeviceManager
@chapter ClutterDeviceManager
Maintains the list of input devices

@section Overview
@code{<clutter-device-manager>} is a singleton object, owned by Clutter,
which maintains the list of @code{<clutter-input-device>}s.

Depending on the backend used by Clutter it is possible to use the
@code{<"device-added">} and @code{<"device-removed">} to monitor
addition and removal of devices.

@code{<clutter-device-manager>} is available since Clutter 1.2

@section Usage
@include defuns-clutter-device-manager.xml.texi

@c %end of fragment
