
@c %start of fragment

@node ClutterTexture
@chapter ClutterTexture
An actor for displaying and manipulating images.

@section Overview
@code{<clutter-texture>} is a base class for displaying and manipulating
pixel buffer type data.

The @code{clutter-texture-set-from-rgb-data} and
@code{clutter-texture-set-from-file} functions are used to copy image
data into texture memory and subsequently realize the texture.

If texture reads are supported by underlying GL implementation,
unrealizing frees image data from texture memory moving to main system
memory. Re-realizing then performs the opposite operation. This process
allows basic management of commonly limited available texture memory.

Note: a ClutterTexture will scale its contents to fit the bounding box
requested using @code{clutter-actor-set-size}. To display an area of a
texture without scaling, you should set the clip area using
@code{clutter-actor-set-clip}.

@section Usage
@include defuns-clutter-texture.xml.texi

@c %end of fragment
