
@c %start of fragment

@node ClutterMedia
@chapter ClutterMedia
An interface for controlling playback of media data

@section Overview
@code{<clutter-media>} is an interface for controlling playback of media
sources.

Clutter core does not provide an implementation of this interface, but
other integration libraries like Clutter-GStreamer implement it to offer
a uniform API for applications.

@code{<clutter-media>} is available since Clutter 0.2

@code{<clutter-media>} is deprecated since Clutter 1.12

@section Usage
@include defuns-clutter-media.xml.texi

@c %end of fragment
