
@c %start of fragment

@node ClutterBehaviourPath
@chapter ClutterBehaviourPath
A behaviour for moving actors along a

@section Overview
@code{<clutter-behaviour-path>} interpolates actors along a defined
path.

A path is described by a @code{<clutter-path>} object. The path can
contain straight line parts and bezier curves. If the path contains
@samp{CLUTTER_PATH_MOVE_TO} parts then the actors will jump to those
coordinates. This can be used make disjoint paths.

When creating a path behaviour in a @code{<clutter-script>}, you can
specify the path property directly as a string. For example:

@example 

@{
  "id"     : "spline-path",
  "type"   : "ClutterBehaviourPath",
  "path"   : "M 50 50 L 100 100",
  "alpha"  : @{
     "timeline" : "main-timeline",
     "function" : "ramp
   @}
@}
@end example

@cartouche 
If the alpha function is a periodic function, i.e. it returns to
0 after reaching @samp{CLUTTER_ALPHA_MAX_ALPHA}, then the actors will walk
the path back to the starting @code{<clutter-knot>}.
@end cartouche

@code{<clutter-behaviour-path>} is available since Clutter 0.2

@section Usage
@include defuns-clutter-behaviour-path.xml.texi

@c %end of fragment
