
@c %start of fragment

@node Undocumented
@chapter Undocumented
The following symbols, if any, have not been properly documented.

@section (gnome clutter)
@defun clutter-interval-get-final interval
@end defun

@defun clutter-interval-get-initial interval
@end defun

@defun clutter-interval-get-interval interval
@end defun

@defun clutter-interval-new type from to
@end defun

@defun clutter-interval-set-final interval val
@end defun

@defun clutter-interval-set-initial interval val
@end defun

@defun clutter-interval-set-interval interval initial final
@end defun

@section (gnome gw clutter)
@deftp Class <clutter-animatable>
@end deftp

@defvar <clutter-event-sequence*>
@end defvar

@defvar <clutter-input-device*>
@end defvar

@defvar clutter-actor-add-constraint-with-name
@end defvar

@defvar clutter-actor-allocate-available-size
@end defvar

@defvar clutter-actor-allocate-preferred-size
@end defvar

@defvar clutter-actor-apply-relative-transform-to-point
@end defvar

@defvar clutter-actor-apply-transform-to-point
@end defvar

@defvar clutter-actor-get-allocation-geometry
@end defvar

@defvar clutter-actor-get-anchor-point-gravity
@end defvar

@defvar clutter-actor-get-clip-to-allocation
@end defvar

@defun clutter-actor-get-content-scaling-filters _
@end defun

@defvar clutter-actor-get-default-paint-volume
@end defvar

@defvar clutter-actor-get-fixed-position-set
@end defvar

@defvar clutter-actor-get-offscreen-redirect
@end defvar

@defvar clutter-actor-get-paint-volume
@end defvar

@defvar clutter-actor-get-transformed-paint-volume
@end defvar

@defun clutter-actor-get-transformed-position _
@end defun

@defvar clutter-actor-get-z-rotation-gravity
@end defvar

@defvar clutter-actor-move-anchor-point-from-gravity
@end defvar

@defvar clutter-actor-remove-all-transitions
@end defvar

@defvar clutter-actor-remove-constraint-by-name
@end defvar

@defvar clutter-actor-set-anchor-point-from-gravity
@end defvar

@defvar clutter-actor-set-child-above-sibling
@end defvar

@defvar clutter-actor-set-child-below-sibling
@end defvar

@defvar clutter-actor-set-clip-to-allocation
@end defvar

@defvar clutter-actor-set-content-scaling-filters
@end defvar

@defvar clutter-actor-set-fixed-position-set
@end defvar

@defvar clutter-actor-set-offscreen-redirect
@end defvar

@defvar clutter-actor-set-scale-with-gravity
@end defvar

@defvar clutter-actor-set-z-rotation-from-gravity
@end defvar

@defvar clutter-align-constraint-get-align-axis
@end defvar

@defvar clutter-align-constraint-set-align-axis
@end defvar

@defvar clutter-animatable-get-initial-state
@end defvar

@defvar clutter-animatable-interpolate-value
@end defvar

@defvar clutter-animator-key-get-property-name
@end defvar

@defun clutter-animator-key-get-property-type _
@end defun

@defvar clutter-animator-property-get-ease-in
@end defvar

@defvar clutter-animator-property-get-interpolation
@end defvar

@defvar clutter-animator-property-set-ease-in
@end defvar

@defvar clutter-animator-property-set-interpolation
@end defvar

@defun clutter-backend-get-font-options _
@end defun

@defvar clutter-base-init
@end defvar

@defvar clutter-bind-constraint-get-coordinate
@end defvar

@defvar clutter-bind-constraint-set-coordinate
@end defvar

@defvar clutter-binding-pool-install-closure
@end defvar

@defvar clutter-binding-pool-override-closure
@end defvar

@defvar clutter-box-layout-get-easing-duration
@end defvar

@defvar clutter-box-layout-get-use-animations
@end defvar

@defvar clutter-box-layout-set-easing-duration
@end defvar

@defvar clutter-box-layout-set-use-animations
@end defvar

@defun clutter-brightness-contrast-effect-get-brightness _
@end defun

@defun clutter-brightness-contrast-effect-get-contrast _
@end defun

@defvar clutter-brightness-contrast-effect-new
@end defvar

@defvar clutter-brightness-contrast-effect-set-brightness
@end defvar

@defvar clutter-brightness-contrast-effect-set-brightness-full
@end defvar

@defvar clutter-brightness-contrast-effect-set-contrast
@end defvar

@defvar clutter-brightness-contrast-effect-set-contrast-full
@end defvar

@defvar clutter-cairo-texture-get-auto-resize
@end defvar

@defun clutter-cairo-texture-get-surface-size _
@end defun

@defvar clutter-cairo-texture-set-auto-resize
@end defvar

@defvar clutter-cairo-texture-set-surface-size
@end defvar

@defvar clutter-container-child-get-property
@end defvar

@defvar clutter-container-child-set-property
@end defvar

@defvar clutter-container-destroy-child-meta
@end defvar

@defvar clutter-container-find-child-by-name
@end defvar

@defvar clutter-desaturate-effect-get-factor
@end defvar

@defvar clutter-desaturate-effect-set-factor
@end defvar

@defvar clutter-device-manager-get-core-device
@end defvar

@defvar clutter-device-manager-get-default
@end defvar

@defun clutter-drag-action-get-drag-threshold _
@end defun

@defun clutter-drag-action-get-motion-coords _
@end defun

@defun clutter-drag-action-get-press-coords _
@end defun

@defvar clutter-drag-action-set-drag-threshold
@end defvar

@defvar clutter-event-get-scroll-direction
@end defvar

@defvar clutter-flow-layout-get-column-spacing
@end defvar

@defun clutter-flow-layout-get-column-width _
@end defun

@defvar clutter-flow-layout-get-orientation
@end defvar

@defvar clutter-flow-layout-set-column-spacing
@end defvar

@defvar clutter-flow-layout-set-column-width
@end defvar

@defun clutter-gesture-action-get-motion-coords _ _
@end defun

@defun clutter-gesture-action-get-press-coords _ _
@end defun

@defun clutter-gesture-action-get-release-coords _ _
@end defun

@defvar clutter-image-error-quark
@end defvar

@defvar clutter-input-device-get-associated-device
@end defvar

@defun clutter-input-device-get-device-coords _
@end defun

@defvar clutter-input-device-get-device-mode
@end defvar

@defvar clutter-input-device-get-device-name
@end defvar

@defvar clutter-input-device-get-device-type
@end defvar

@defvar clutter-input-device-get-grabbed-actor
@end defvar

@defvar clutter-input-device-get-pointer-actor
@end defvar

@defvar clutter-input-device-get-pointer-stage
@end defvar

@defun clutter-input-device-get-slave-devices _
@end defun

@defun clutter-input-device-keycode-to-evdev _ _
@end defun

@defvar clutter-input-device-update-from-event
@end defvar

@defvar clutter-knot-equal
@end defvar

@defvar clutter-layout-manager-begin-animation
@end defvar

@defvar clutter-layout-manager-child-get-property
@end defvar

@defvar clutter-layout-manager-child-set-property
@end defvar

@defvar clutter-layout-manager-end-animation
@end defvar

@defvar clutter-layout-manager-find-child-property
@end defvar

@defvar clutter-layout-manager-get-animation-progress
@end defvar

@defvar clutter-layout-manager-get-child-meta
@end defvar

@defun clutter-layout-manager-get-preferred-height _ _ _
@end defun

@defun clutter-layout-manager-get-preferred-width _ _ _
@end defun

@defvar clutter-layout-manager-layout-changed
@end defvar

@defvar clutter-layout-manager-set-container
@end defvar

@defvar clutter-media-get-subtitle-font-name
@end defvar

@defvar clutter-media-set-subtitle-font-name
@end defvar

@defun clutter-offscreen-effect-get-target-size _
@end defun

@defvar clutter-offscreen-effect-paint-target
@end defvar

@defvar clutter-paint-node-add-texture-rectangle
@end defvar

@defvar clutter-paint-volume-set-from-allocation
@end defvar

@defvar clutter-property-transition-get-property-name
@end defvar

@defvar clutter-property-transition-set-property-name
@end defvar

@defvar clutter-script-error-quark
@end defvar

@defvar clutter-script-get-translation-domain
@end defvar

@defvar clutter-script-set-translation-domain
@end defvar

@defvar clutter-shader-effect-set-shader-source
@end defvar

@defvar clutter-shader-effect-set-uniform-value
@end defvar

@defvar clutter-shader-error-quark
@end defvar

@defvar clutter-stage-get-motion-events-enabled
@end defvar

@defvar clutter-stage-get-throttle-motion-events
@end defvar

@defvar clutter-stage-manager-get-default-stage
@end defvar

@defvar clutter-stage-set-motion-events-enabled
@end defvar

@defvar clutter-stage-set-throttle-motion-events
@end defvar

@defvar clutter-state-key-get-source-state-name
@end defvar

@defvar clutter-state-key-get-target-state-name
@end defvar

@defvar clutter-table-layout-get-column-count
@end defvar

@defvar clutter-table-layout-get-column-spacing
@end defvar

@defvar clutter-table-layout-get-easing-duration
@end defvar

@defvar clutter-table-layout-get-easing-mode
@end defvar

@defvar clutter-table-layout-get-row-spacing
@end defvar

@defvar clutter-table-layout-get-use-animations
@end defvar

@defvar clutter-table-layout-set-column-spacing
@end defvar

@defvar clutter-table-layout-set-easing-duration
@end defvar

@defvar clutter-table-layout-set-easing-mode
@end defvar

@defvar clutter-table-layout-set-row-spacing
@end defvar

@defvar clutter-table-layout-set-use-animations
@end defvar

@defvar clutter-text-buffer-emit-deleted-text
@end defvar

@defvar clutter-text-buffer-emit-inserted-text
@end defvar

@defvar clutter-text-get-font-description
@end defvar

@defvar clutter-text-get-selected-text-color
@end defvar

@defvar clutter-text-set-selected-text-color
@end defvar

@defvar clutter-texture-error-quark
@end defvar

@defvar clutter-texture-get-filter-quality
@end defvar

@defvar clutter-texture-get-keep-aspect-ratio
@end defvar

@defvar clutter-texture-set-keep-aspect-ratio
@end defvar

@defvar clutter-transition-get-remove-on-complete
@end defvar

@defvar clutter-transition-set-remove-on-complete
@end defvar


@c %end of fragment
