
@c %start of fragment

@node Undocumented
@chapter Undocumented
The following symbols, if any, have not been properly documented.

@section (gnome gw clutter)
@deftp Class <clutter-animatable>
@end deftp

@defvar <clutter-input-device*>
@end defvar

@defvar clutter-actor-add-constraint-with-name
@end defvar

@defvar clutter-actor-allocate-available-size
@end defvar

@defvar clutter-actor-allocate-preferred-size
@end defvar

@defvar clutter-actor-apply-relative-transform-to-point
@end defvar

@defvar clutter-actor-apply-transform-to-point
@end defvar

@defvar clutter-actor-get-allocation-geometry
@end defvar

@defvar clutter-actor-get-anchor-point-gravity
@end defvar

@defvar clutter-actor-get-clip-to-allocation
@end defvar

@defvar clutter-actor-get-fixed-position-set
@end defvar

@defun clutter-actor-get-transformed-position _
@end defun

@defvar clutter-actor-get-z-rotation-gravity
@end defvar

@defvar clutter-actor-meta-get-actor
@end defvar

@defvar clutter-actor-meta-get-enabled
@end defvar

@defvar clutter-actor-meta-get-name
@end defvar

@defvar clutter-actor-meta-set-enabled
@end defvar

@defvar clutter-actor-meta-set-name
@end defvar

@defvar clutter-actor-move-anchor-point-from-gravity
@end defvar

@defvar clutter-actor-remove-constraint-by-name
@end defvar

@defvar clutter-actor-set-anchor-point-from-gravity
@end defvar

@defvar clutter-actor-set-clip-to-allocation
@end defvar

@defvar clutter-actor-set-fixed-position-set
@end defvar

@defvar clutter-actor-set-scale-with-gravity
@end defvar

@defvar clutter-actor-set-shader-param-float
@end defvar

@defvar clutter-actor-set-z-rotation-from-gravity
@end defvar

@defvar clutter-align-constraint-get-align-axis
@end defvar

@defvar clutter-align-constraint-get-factor
@end defvar

@defvar clutter-align-constraint-get-source
@end defvar

@defvar clutter-align-constraint-new
@end defvar

@defvar clutter-align-constraint-set-align-axis
@end defvar

@defvar clutter-align-constraint-set-factor
@end defvar

@defvar clutter-align-constraint-set-source
@end defvar

@defvar clutter-animatable-get-initial-state
@end defvar

@defvar clutter-animator-key-get-property-name
@end defvar

@defun clutter-animator-key-get-property-type _
@end defun

@defvar clutter-animator-property-get-ease-in
@end defvar

@defvar clutter-animator-property-get-interpolation
@end defvar

@defvar clutter-animator-property-set-ease-in
@end defvar

@defvar clutter-animator-property-set-interpolation
@end defvar

@defvar clutter-backend-get-double-click-distance
@end defvar

@defvar clutter-backend-get-double-click-time
@end defvar

@defun clutter-backend-get-font-options _
@end defun

@defvar clutter-backend-set-double-click-distance
@end defvar

@defvar clutter-backend-set-double-click-time
@end defvar

@defvar clutter-base-init
@end defvar

@defvar clutter-behaviour-ellipse-get-angle-end
@end defvar

@defvar clutter-behaviour-ellipse-get-angle-start
@end defvar

@defvar clutter-behaviour-ellipse-get-angle-tilt
@end defvar

@defun clutter-behaviour-ellipse-get-center _
@end defun

@defvar clutter-behaviour-ellipse-get-direction
@end defvar

@defvar clutter-behaviour-ellipse-get-height
@end defvar

@defvar clutter-behaviour-ellipse-set-angle-end
@end defvar

@defvar clutter-behaviour-ellipse-set-angle-start
@end defvar

@defvar clutter-behaviour-ellipse-set-angle-tilt
@end defvar

@defvar clutter-behaviour-ellipse-set-center
@end defvar

@defvar clutter-behaviour-ellipse-set-direction
@end defvar

@defvar clutter-behaviour-ellipse-set-height
@end defvar

@defun clutter-behaviour-opacity-get-bounds _
@end defun

@defvar clutter-behaviour-opacity-set-bounds
@end defvar

@defvar clutter-behaviour-path-new-with-description
@end defvar

@defvar clutter-behaviour-path-new-with-knots
@end defvar

@defvar clutter-behaviour-rotate-get-direction
@end defvar

@defvar clutter-behaviour-rotate-set-direction
@end defvar

@defvar clutter-bind-constraint-get-coordinate
@end defvar

@defvar clutter-bind-constraint-get-offset
@end defvar

@defvar clutter-bind-constraint-get-source
@end defvar

@defvar clutter-bind-constraint-new
@end defvar

@defvar clutter-bind-constraint-set-coordinate
@end defvar

@defvar clutter-bind-constraint-set-offset
@end defvar

@defvar clutter-bind-constraint-set-source
@end defvar

@defvar clutter-binding-pool-install-closure
@end defvar

@defvar clutter-binding-pool-override-closure
@end defvar

@defvar clutter-blur-effect-new
@end defvar

@defvar clutter-box-layout-get-easing-duration
@end defvar

@defvar clutter-box-layout-get-use-animations
@end defvar

@defvar clutter-box-layout-set-easing-duration
@end defvar

@defvar clutter-box-layout-set-use-animations
@end defvar

@defun clutter-cairo-texture-get-surface-size _
@end defun

@defvar clutter-cairo-texture-set-surface-size
@end defvar

@defvar clutter-click-action-get-button
@end defvar

@defvar clutter-click-action-new
@end defvar

@defvar clutter-click-action-release
@end defvar

@defvar clutter-colorize-effect-get-tint
@end defvar

@defvar clutter-colorize-effect-new
@end defvar

@defvar clutter-colorize-effect-set-tint
@end defvar

@defvar clutter-container-child-get-property
@end defvar

@defvar clutter-container-child-set-property
@end defvar

@defvar clutter-container-destroy-child-meta
@end defvar

@defvar clutter-container-find-child-by-name
@end defvar

@defun clutter-deform-effect-get-n-tiles _
@end defun

@defvar clutter-deform-effect-invalidate
@end defvar

@defvar clutter-deform-effect-set-n-tiles
@end defvar

@defvar clutter-desaturate-effect-get-factor
@end defvar

@defvar clutter-desaturate-effect-new
@end defvar

@defvar clutter-desaturate-effect-set-factor
@end defvar

@defvar clutter-device-manager-get-core-device
@end defvar

@defvar clutter-device-manager-get-default
@end defvar

@defvar clutter-drag-action-get-drag-axis
@end defvar

@defvar clutter-drag-action-get-drag-handle
@end defvar

@defun clutter-drag-action-get-drag-threshold _
@end defun

@defun clutter-drag-action-get-motion-coords _
@end defun

@defun clutter-drag-action-get-press-coords _
@end defun

@defvar clutter-drag-action-new
@end defvar

@defvar clutter-drag-action-set-drag-axis
@end defvar

@defvar clutter-drag-action-set-drag-handle
@end defvar

@defvar clutter-drag-action-set-drag-threshold
@end defvar

@defvar clutter-event-get-scroll-direction
@end defvar

@defvar clutter-flow-layout-get-column-spacing
@end defvar

@defun clutter-flow-layout-get-column-width _
@end defun

@defvar clutter-flow-layout-get-orientation
@end defvar

@defvar clutter-flow-layout-set-column-spacing
@end defvar

@defvar clutter-flow-layout-set-column-width
@end defvar

@defun clutter-input-device-get-device-coords _
@end defun

@defvar clutter-input-device-get-device-name
@end defvar

@defvar clutter-input-device-get-device-type
@end defvar

@defvar clutter-input-device-get-pointer-actor
@end defvar

@defvar clutter-input-device-get-pointer-stage
@end defvar

@defvar clutter-input-device-update-from-event
@end defvar

@defvar clutter-layout-manager-begin-animation
@end defvar

@defvar clutter-layout-manager-child-get-property
@end defvar

@defvar clutter-layout-manager-child-set-property
@end defvar

@defvar clutter-layout-manager-end-animation
@end defvar

@defvar clutter-layout-manager-find-child-property
@end defvar

@defvar clutter-layout-manager-get-animation-progress
@end defvar

@defvar clutter-layout-manager-get-child-meta
@end defvar

@defun clutter-layout-manager-get-preferred-height _ _ _
@end defun

@defun clutter-layout-manager-get-preferred-width _ _ _
@end defun

@defvar clutter-layout-manager-layout-changed
@end defvar

@defvar clutter-layout-manager-set-container
@end defvar

@defvar clutter-media-get-subtitle-font-name
@end defvar

@defvar clutter-media-set-subtitle-font-name
@end defvar

@defvar clutter-offscreen-effect-paint-target
@end defvar

@defvar clutter-page-turn-effect-get-angle
@end defvar

@defvar clutter-page-turn-effect-get-period
@end defvar

@defvar clutter-page-turn-effect-get-radius
@end defvar

@defvar clutter-page-turn-effect-new
@end defvar

@defvar clutter-page-turn-effect-set-angle
@end defvar

@defvar clutter-page-turn-effect-set-period
@end defvar

@defvar clutter-page-turn-effect-set-radius
@end defvar

@defvar clutter-redraw
@end defvar

@defvar clutter-script-error-quark
@end defvar

@defvar clutter-settings-get-default
@end defvar

@defvar clutter-shader-effect-set-shader-source
@end defvar

@defvar clutter-shader-effect-set-uniform-value
@end defvar

@defvar clutter-shader-error-quark
@end defvar

@defvar clutter-stage-get-throttle-motion-events
@end defvar

@defvar clutter-stage-manager-get-default-stage
@end defvar

@defvar clutter-stage-manager-set-default-stage
@end defvar

@defvar clutter-stage-set-throttle-motion-events
@end defvar

@defvar clutter-state-get-animator
@end defvar

@defvar clutter-state-get-duration
@end defvar

@defun clutter-state-get-keys _ _ _ _ _
@end defun

@defvar clutter-state-get-state
@end defvar

@defun clutter-state-get-states _
@end defun

@defvar clutter-state-get-timeline
@end defvar

@defvar clutter-state-key-get-mode
@end defvar

@defvar clutter-state-key-get-object
@end defvar

@defvar clutter-state-key-get-post-delay
@end defvar

@defvar clutter-state-key-get-pre-delay
@end defvar

@defvar clutter-state-key-get-property-name
@end defvar

@defun clutter-state-key-get-property-type _
@end defun

@defvar clutter-state-key-get-source-state-name
@end defvar

@defvar clutter-state-key-get-target-state-name
@end defvar

@defvar clutter-state-key-get-value
@end defvar

@defvar clutter-state-new
@end defvar

@defvar clutter-state-remove-key
@end defvar

@defvar clutter-state-set-animator
@end defvar

@defvar clutter-state-set-duration
@end defvar

@defvar clutter-state-set-key
@end defvar

@defvar clutter-state-set-state
@end defvar

@defvar clutter-state-warp-to-state
@end defvar

@defun clutter-table-layout-get-alignment _ _
@end defun

@defvar clutter-table-layout-get-column-count
@end defvar

@defvar clutter-table-layout-get-column-spacing
@end defvar

@defvar clutter-table-layout-get-easing-duration
@end defvar

@defvar clutter-table-layout-get-easing-mode
@end defvar

@defun clutter-table-layout-get-expand _ _
@end defun

@defun clutter-table-layout-get-fill _ _
@end defun

@defvar clutter-table-layout-get-row-count
@end defvar

@defvar clutter-table-layout-get-row-spacing
@end defvar

@defun clutter-table-layout-get-span _ _
@end defun

@defvar clutter-table-layout-get-use-animations
@end defvar

@defvar clutter-table-layout-new
@end defvar

@defvar clutter-table-layout-pack
@end defvar

@defvar clutter-table-layout-set-alignment
@end defvar

@defvar clutter-table-layout-set-column-spacing
@end defvar

@defvar clutter-table-layout-set-easing-duration
@end defvar

@defvar clutter-table-layout-set-easing-mode
@end defvar

@defvar clutter-table-layout-set-expand
@end defvar

@defvar clutter-table-layout-set-fill
@end defvar

@defvar clutter-table-layout-set-row-spacing
@end defvar

@defvar clutter-table-layout-set-span
@end defvar

@defvar clutter-table-layout-set-use-animations
@end defvar

@defvar clutter-text-get-font-description
@end defvar

@defvar clutter-texture-error-quark
@end defvar

@defvar clutter-texture-get-filter-quality
@end defvar

@defvar clutter-texture-get-keep-aspect-ratio
@end defvar

@defvar clutter-texture-set-keep-aspect-ratio
@end defvar


@c %end of fragment
